import { Formateur } from "../interfaces/formateur";

export const formateurs: Formateur[] = [
  {
    id: 1,
    nom: "Johnson",
    prenom: "Michael",
    telephone: "+1 202 555 0134",
    cin: 87451236,
    photo: "photos/johnson_michael.jpg",
    cv: "cv/johnson_michael.pdf",
    specialite: ["programmation", "bases", "logique"],
  },
  {
    id: 2,
    nom: "Smith",
    prenom: "Emily",
    telephone: "+1 202 555 0198",
    cin: 98124563,
    photo: "photos/smith_emily.jpg",
    cv: "cv/smith_emily.pdf",
    specialite: ["html", "css", "javascript", "frontend"],
  },
  {
    id: 3,
    nom: "Brown",
    prenom: "Christopher",
    telephone: "+1 202 555 0172",
    cin: 72519463,
    photo: "photos/brown_christopher.jpg",
    cv: "cv/brown_christopher.pdf",
    specialite: ["api", "node.js", "express", "backend"],
  },
  {
    id: 4,
    nom: "Wilson",
    prenom: "Olivia",
    telephone: "+1 202 555 0149",
    cin: 65741892,
    photo: "photos/wilson_olivia.jpg",
    cv: "cv/wilson_olivia.pdf",
    specialite: ["design", "ux", "ui", "interfaces"],
  },
  {
    id: 5,
    nom: "Anderson",
    prenom: "James",
    telephone: "+1 202 555 0158",
    cin: 55891476,
    photo: "photos/anderson_james.jpg",
    cv: "cv/anderson_james.pdf",
    specialite: ["linux", "administration", "serveurs"],
  },
  {
    id: 6,
    nom: "Miller",
    prenom: "Sophia",
    telephone: "+1 202 555 0183",
    cin: 44231758,
    photo: "photos/miller_sophia.jpg",
    cv: "cv/miller_sophia.pdf",
    specialite: ["mobile", "flutter", "dart"],
  },
  {
    id: 7,
    nom: "Davis",
    prenom: "Benjamin",
    telephone: "+1 202 555 0117",
    cin: 33987415,
    photo: "photos/davis_benjamin.jpg",
    cv: "cv/davis_benjamin.pdf",
    specialite: ["ia", "machine learning", "algorithmes"],
  },
  {
    id: 8,
    nom: "Thompson",
    prenom: "Charlotte",
    telephone: "+1 202 555 0104",
    cin: 78451293,
    photo: "photos/thompson_charlotte.jpg",
    cv: "cv/thompson_charlotte.pdf",
    specialite: ["cybersécurité", "sécurité", "réseaux"],
  },
];
