import { Formation } from "../interfaces/formation";

export const formations: Formation[] = [
  {
    id: 1,
    titre: "Initiation à la Programmation",
    description: "Découverte des bases de la programmation à travers des exercices simples et progressifs. Les participants apprendront la logique de programmation, les structures de contrôle et les bonnes pratiques pour débuter dans le développement logiciel.",
    chargeHoraire: 20,
    difficulte: "Débutant",
    motCles: ["programmation", "bases", "logique","initiation"],
    pdf: "programmes/initiation_programmation.pdf",
  },
  {
    id: 2,
    titre: "Développement Web Front-End",
    description: "Apprentissage du HTML, CSS et JavaScript pour créer des interfaces modernes et interactives. Le cours couvre la mise en page, le design responsive et les meilleures pratiques pour le développement front-end.",
    chargeHoraire: 35,
    difficulte: "Intermédiaire",
    motCles: ["html", "css", "javascript", "frontend","web","développement"],
    pdf: "programmes/front_end.pdf",
  },
  {
    id: 3,
    titre: "Développement Web Back-End",
    description: "Création d'API et gestion des données avec Node.js, Express et bases de données. Les participants apprendront à structurer une application back-end, gérer les routes, sécuriser les données et intégrer les services web.",
    chargeHoraire: 40,
    difficulte: "Intermédiaire",
    motCles: ["api", "node.js", "express", "backend","web","développement"],
    pdf: "programmes/back_end.pdf",
  },
  {
    id: 4,
    titre: "Bases de Données SQL",
    description: "Compréhension et manipulation des bases relationnelles à l’aide de SQL. Le cours inclut la création de tables, les requêtes SELECT, INSERT, UPDATE, DELETE, ainsi que l'optimisation et les jointures pour gérer efficacement les données.",
    chargeHoraire: 25,
    difficulte: "Débutant",
    motCles: ["sql", "base","données", "requêtes"],
    pdf: "programmes/sql.pdf",
  },
  {
    id: 5,
    titre: "Développement Mobile Flutter",
    description: "Créer des applications mobiles multiplateformes avec Flutter et Dart. Le cours aborde la création d’interfaces réactives, la gestion de l’état, les widgets et la publication d’applications sur iOS et Android.",
    chargeHoraire: 45,
    difficulte: "Avancé",
    motCles: ["flutter", "dart", "mobile","développement"],
    pdf: "programmes/flutter.pdf",
  },
  {
    id: 6,
    titre: "Administration Systèmes Linux",
    description: "Maîtriser les commandes essentielles et l'administration de systèmes Linux. Les participants apprendront la gestion des utilisateurs, des fichiers, des permissions, ainsi que la configuration des services et la sécurité des serveurs.",
    chargeHoraire: 30,
    difficulte: "Intermédiaire",
    motCles: ["linux", "administration", "serveurs","système"],
    pdf: "programmes/linux_admin.pdf",
  },
  {
    id: 7,
    titre: "Cybersécurité – Fondamentaux",
    description: "Introduction aux concepts, menaces et bonnes pratiques en cybersécurité. Le cours couvre les types d’attaques, la protection des systèmes et des réseaux, ainsi que les bases de la sécurité informatique pour les professionnels débutants.",
    chargeHoraire: 28,
    difficulte: "Débutant",
    motCles: ["cybersécurité", "sécurité", "réseaux"],
    pdf: "programmes/cybersecurite.pdf",
  },
  {
    id: 8,
    titre: "Intelligence Artificielle et Machine Learning",
    description: "Comprendre les modèles IA, les algorithmes de Machine Learning et leurs applications pratiques. Le cours aborde l’apprentissage supervisé et non supervisé, le traitement de données, la création de modèles prédictifs et l’intégration dans des projets réels.",
    chargeHoraire: 50,
    difficulte: "Avancé",
    motCles: ["ia","ai","machine learning", "algorithmes","intelligence","artificielle"],
    pdf: "programmes/ia_ml.pdf",
  },
  {
    id: 9,
    titre: "UX/UI Design",
    description: "Créer des interfaces intuitives avec les principes d’ergonomie et de design moderne. Les participants apprendront à concevoir des maquettes, à améliorer l’expérience utilisateur et à appliquer des principes de design responsive.",
    chargeHoraire: 32,
    difficulte: "Intermédiaire",
    motCles: ["design", "ux", "ui", "interfaces"],
    pdf: "programmes/ux_ui.pdf",
  },
  {
    id: 10,
    titre: "Réseaux Informatiques",
    description: "Comprendre les concepts fondamentaux des réseaux : OSI, TCP/IP, topologies et sécurité. Le cours inclut la configuration de réseaux locaux, la gestion des routeurs et des switches, ainsi que les bonnes pratiques pour sécuriser les communications.",
    chargeHoraire: 36,
    difficulte: "Intermédiaire",
    motCles: ["réseaux", "tcp/ip", "communication"],
    pdf: "programmes/reseaux.pdf",
  },
];
